creation_rules:
  - path_regex: '(^|/)bootstrap\.yaml$'
    age: age144e8hx0us4qxyfr7mzu6cxa8dj7vczseq4m73njcyhxzzsuhtfzq5prq6k
  - path_regex: '(^|/)runtime\.yaml$'
    age: age1sx0f576tf3es44yc9u4qnqlhywuy6q0nw33p7p40ngms7ryck4yqh0anjq
