# jupiter: LUKS2(TPM2 自動解錠はインストール後に systemd-cryptenroll で登録)
# + btrfs subvolume + zstd。デバイス名はマシン確定時に実値へ(インストール前ゲート 1)
{ ... }:
{
  disko.devices.disk.main = {
    type = "disk";
    device = "/dev/nvme0n1"; # ★実機確定時に必ず実デバイスへ変更
    content = {
      type = "gpt";
      partitions = {
        ESP = {
          size = "1G";
          type = "EF00";
          content = {
            type = "filesystem";
            format = "vfat";
            mountpoint = "/boot";
            mountOptions = [ "umask=0077" ];
          };
        };
        luks = {
          size = "100%";
          content = {
            type = "luks";
            name = "cryptroot";
            settings.allowDiscards = true;
            # initrd が TPM を見に行く口。これが無いと enroll だけしても解錠されない。
            # 封印する PCR は enroll 側で決める(runbook 参照)。
            settings.crypttabExtraOpts = [ "tpm2-device=auto" ];
            # インストール時(nixos-anywhere)だけが読む非対話パスワード。
            # nixos-anywhere の --disk-encryption-keys /tmp/secret.key <src> とペア。
            #
            # 必ずトップレベルの passwordFile に置くこと。settings 配下(旧:
            # settings.keyFile)には絶対に置かない。disko の _config
            # (lib/types/luks.nix)は NixOS 側 boot.initrd.luks.devices.cryptroot
            # へ config.settings だけをマージし、トップレベルの passwordFile は
            # 一切伝播しない。つまり passwordFile はここでの format/mount 一発物
            # (disko 自身が --key-file <(set +x; echo -n "$(cat passwordFile)"; set -x)
            # として使う。set +x はトレース出力にパスワードを出さないため)にしか
            # 効かず、実機起動時の initrd 設定には出てこない。
            #
            # settings 配下に置くと boot.initrd.luks.devices.cryptroot.keyFile が
            # 非 null になり、systemd-cryptsetup の
            # attach_luks_or_plain_or_bitlk_by_tpm2 が LUKS2 ヘッダ内のトークン探索
            # (attach_luks2_by_tpm2_via_plugin / find_tpm2_auto_data)を一切試さず
            # 「keyFile に封印済みブロブがある」経路へ無条件で入る。実機の initrd に
            # /tmp/secret.key は存在しないため毎回失敗し、対話パスフレーズへ
            # フォールバックして TPM 自動解錠が効かなくなる。
            #
            # passwordFile が設定されていれば askPassword の既定
            # (config.keyFile == null && config.passwordFile == null &&
            # !(config.settings ? "keyFile") && !autogeneratedPassword)は偽になり、
            # インストール時にパスワードを対話入力させられることもない。
            passwordFile = "/tmp/secret.key";
            # TPM2 enroll は初回起動後: sudo systemd-cryptenroll --tpm2-device=auto <dev>
            content = {
              type = "btrfs";
              extraArgs = [ "-f" ];
              subvolumes = {
                "@root" = {
                  mountpoint = "/";
                  mountOptions = [
                    "compress=zstd"
                    "noatime"
                  ];
                };
                "@home" = {
                  mountpoint = "/home";
                  mountOptions = [
                    "compress=zstd"
                    "noatime"
                  ];
                };
                "@nix" = {
                  mountpoint = "/nix";
                  mountOptions = [
                    "compress=zstd"
                    "noatime"
                  ];
                };
                "@swap" = {
                  mountpoint = "/.swap";
                  swap.swapfile.size = "16G";
                };
              };
            };
          };
        };
      };
    };
  };
}
