{ lib, config, ... }:
let
  # alias の唯一の定義(bash / fish 両方へ展開)
  aliases = {
    ll = "ls -la";
    n = "nvim";
    g = "git";
    gs = "git status -sb";
    gco = "git checkout";
    gci = "git commit -m";
    gcia = "git commit --amend";
    gl = "git log --graph --decorate --name-status";
    gg = "git grep";
    gd = "git diff";
    ga = "git add";
    gb = "git branch";
    gP = "git push";
    gPf = "git push --force-with-lease";
    gPF = "git push --force";
    gp = "git pull";
    gr = "git rebase";
    grc = "git rebase --continue";
    gra = "git rebase --abort";
    gm = "git merge";
    gmc = "git merge --continue";
    gma = "git merge --abort";
    gcl = "git clean --force";
  };
  fishAliases = lib.concatStringsSep "\n" (
    lib.mapAttrsToList (k: v: "alias ${k} ${lib.escapeShellArg v}") aliases
  );
in
{
  programs.bash = {
    enable = true;
    initExtra = ''
      if [[ ! "$PATH" =~ "$HOME/.local/bin" ]]; then
        export PATH="$HOME/.local/bin:$PATH"
      fi
    '';
    shellAliases = aliases;
  };

  # fish は dotfiles が config.fish / PATH を所有する(#8(b))。
  # 注意: ~/.config/fish は dotfiles repo への symlink(実測)のため、
  # conf.d へ直接書くと dotfiles の作業ツリーを汚染し、git clean で供給が消える。
  # → dotfiles の外(~/.local/share/nix-home/)に置き、dotfiles の config.fish が
  #   source する方式にする(Task 15 Step 4 で dotfiles に source 行を追加)
  xdg.dataFile."nix-home/env.fish".text = ''
    # generated by home-manager (nix-config)。PATH はここでは変更しない
    set -gx EDITOR nvim
    set -gx VISUAL nvim
    set -gx PAGER less
    set -gx LESS -R
    ${
      lib.optionalString (config.programs.nh.enable or false) ''
        set -gx NH_FLAKE ${config.programs.nh.flake}
      ''
    }${fishAliases}
  '';
  # NH_FLAKE: HM の programs.nh は sessionVariables 経由で設定するが、
  # fish には届かないため(#8(b))env.fish で供給する(dotfiles が source)
}
